# 🧼 Cleaning Dirty Data (Missing Values & Type Fixes)

## 🔹 LEARNING GOALS:
- Detect and count missing values (`NaN`)
- Fill or drop missing data
- Convert column data types safely
- Understand the difference between `NaN`, `None`, `""`, and type mismatches

### 🧪 1. Load a Messy Dataset

In [ ]:
import pandas as pd
import numpy as np

data = {
    "Name": ["Alice", "Bob", "Charlie", "David", None],
    "Age": ["25", "thirty", 35, np.nan, "40"],
    "Signup Date": ["2022-01-01", "not a date", "2022/03/01", None, "April 5, 2022"],
    "Score": [95.5, None, 88.0, 92.5, ""]
}

df = pd.DataFrame(data)
df

      Name     Age    Signup Date Score
0    Alice      25     2022-01-01  95.5
1      Bob  thirty     not a date  None
2  Charlie      35     2022/03/01  88.0
3    David     NaN           None  92.5
4     None      40  April 5, 2022

### 🧯 2. Detecting Missing or Broken Values

In [ ]:
df.isnull()

    Name    Age  Signup Date  Score
0  False  False        False  False
1  False  False        False   True
2  False  False        False  False
3  False   True         True  False
4   True  False        False  False

In [ ]:
df.isnull().sum()

Name           1
Age            1
Signup Date    1
Score          1
dtype: int64

In [ ]:
df[df.isnull().any(axis=1)]

    Name     Age    Signup Date Score
1    Bob  thirty     not a date  None
3  David     NaN           None  92.5
4   None      40  April 5, 2022

### 🧹 3. Cleaning Strategy Options

In [ ]:
df.fillna({
    "Name": "Unknown",
    "Age": -1,
    "Signup Date": "1970-01-01",
    "Score": 0.0
})

      Name     Age    Signup Date Score
0    Alice      25     2022-01-01  95.5
1      Bob  thirty     not a date   0.0
2  Charlie      35     2022/03/01  88.0
3    David      -1     1970-01-01  92.5
4  Unknown      40  April 5, 2022

In [ ]:
df.dropna()

      Name Age Signup Date Score
0    Alice  25  2022-01-01  95.5
2  Charlie  35  2022/03/01  88.0

### 🧬 4. Data Type Fixes

In [ ]:
df.dtypes

Name           object
Age            object
Signup Date    object
Score          object
dtype: object

In [ ]:
df["Age"] = pd.to_numeric(df["Age"], errors="coerce")
df["Score"] = pd.to_numeric(df["Score"], errors="coerce")
df["Signup Date"] = pd.to_datetime(df["Signup Date"], errors="coerce")
df.dtypes

Name                   object
Age                   float64
Signup Date    datetime64[ns]
Score                 float64
dtype: object

### 🩹 5. Impute (Fill In) Fixed Missing Values

In [ ]:
df["Age"].fillna(df["Age"].median(), inplace=True)
df["Score"].fillna(df["Score"].mean(), inplace=True)

/tmp/ipykernel_11591/1713118361.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Age"].fillna(df["Age"].median(), inplace=True)
/tmp/ipykernel_11591/1713118361.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Score"].fillna(df["Score"].mean(), inplace=True)

In [ ]:
df["Signup Date"].fillna(df["Signup Date"].min(), inplace=True)

/tmp/ipykernel_11591/3000949103.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Signup Date"].fillna(df["Signup Date"].min(), inplace=True)

In [ ]:
df["Name"].fillna("Unknown", inplace=True)

/tmp/ipykernel_11591/626038248.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Name"].fillna("Unknown", inplace=True)

### 🤓 6. Cleaned Data Review

In [ ]:
df.info()

In [ ]:
df.describe(include="all")

### 🧪 Try It Yourself

Modify the `data` dictionary at the top of this notebook. Add:
- A new column with some `None` and `""` values
- At least one row with all columns filled incorrectly
Then re-run the notebook and fix it step-by-step.

In [ ]:
import pandas as pd
import numpy as np

data = {
    "Name": ["Alice", "Bob", "Charlie", "David", None, 123],
    "Age": ["25", "thirty", 35, np.nan, "40", "??"],
    "Signup Date": ["2022-01-01", "not a date", "2022/03/01", None, "April 5, 2022", "yesterday"],
    "Score": [95.5, None, 88.0, 92.5, "", "bad"],
    "Feedback": ["Good", "", None, "Excellent", "", 999]  # NEW messy column
}

df = pd.DataFrame(data)
print("Original Dirty Data:")
print(df)

Original Dirty Data:
      Name     Age    Signup Date Score   Feedback
0    Alice      25     2022-01-01  95.5       Good
1      Bob  thirty     not a date  None
2  Charlie      35     2022/03/01  88.0       None
3    David     NaN           None  92.5  Excellent
4     None      40  April 5, 2022
5      123      ??      yesterday   bad        999

### 🧠 Mini-Challenge

> 🗂 Load `"data/survey.csv"` and:
- Identify which columns have missing values
- Use `.isnull().sum()` to get a null report
- Use a mix of `.fillna()`, `.dropna()`, and `pd.to_numeric()` or `pd.to_datetime()` to clean it
- Print a summary with `.info()` and `.describe()`

In [ ]:
#1
print("\nMissing values (boolean map):")
print(df.isnull())

print("\nMissing values per column:")
print(df.isnull().sum())

print("\nRows with ANY missing values:")
print(df[df.isnull().any(axis=1)])

Missing values (boolean map):
    Name    Age  Signup Date  Score  Feedback
0  False  False        False  False     False
1  False  False        False   True     False
2  False  False        False  False      True
3  False   True         True  False     False
4   True  False        False  False     False
5  False  False        False  False     False

Missing values per column:
Name           1
Age            1
Signup Date    1
Score          1
Feedback       1
dtype: int64

Rows with ANY missing values:
      Name     Age    Signup Date Score   Feedback
1      Bob  thirty     not a date  None
2  Charlie      35     2022/03/01  88.0       None
3    David     NaN           None  92.5  Excellent
4     None      40  April 5, 2022

In [ ]:
#2
# Convert Age and Score to numeric
df["Age"] = pd.to_numeric(df["Age"], errors="coerce")
df["Score"] = pd.to_numeric(df["Score"], errors="coerce")

# Convert dates
df["Signup Date"] = pd.to_datetime(df["Signup Date"], errors="coerce")

print("\nData types after conversion:")
print(df.dtypes)

Data types after conversion:
Name                   object
Age                   float64
Signup Date    datetime64[ns]
Score                 float64
Feedback               object
dtype: object

In [ ]:
#3
# Fill numeric columns
df["Age"].fillna(df["Age"].median(), inplace=True)
df["Score"].fillna(df["Score"].mean(), inplace=True)

# Fill dates with earliest valid date
df["Signup Date"].fillna(df["Signup Date"].min(), inplace=True)

# Fill text columns
df["Name"].fillna("Unknown", inplace=True)
df["Feedback"].replace("", np.nan, inplace=True)  # treat "" as missing
df["Feedback"].fillna("No Feedback", inplace=True)

/tmp/ipykernel_11591/1330070607.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Age"].fillna(df["Age"].median(), inplace=True)
/tmp/ipykernel_11591/1330070607.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Score"].fillna(df["Score"].mean(), inplace=True)
/tmp/ipykernel_11591/1330070607.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Signup Date"].fillna(df["Signup Date"].min(), inplace=True)
/tmp/ipykernel_11591/1330070607.py:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Name"].fillna("Unknown", inplace=True)
/tmp/ipykernel_11591/1330070607.py:11: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Feedback"].replace("", np.nan, inplace=True)  # treat "" as missing
/tmp/ipykernel_11591/1330070607.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Feedback"].fillna("No Feedback", inplace=True)

### 🧠 Mini-Challenge

> 🗂 Load `"data/survey.csv"` and:
- Identify which columns have missing values
- Use `.isnull().sum()` to get a null report
- Use a mix of `.fillna()`, `.dropna()`, and `pd.to_numeric()` or `pd.to_datetime()` to clean it
- Print a summary with `.info()` and `.describe()

In [ ]:
df = pd.read_csv("data/survey.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'data/survey.csv'

In [ ]:
print("\nMissing values per column:")
print(df.isnull().sum())

Missing values per column:
Name           0
Age            0
Signup Date    0
Score          0
dtype: int64

In [ ]:
# Example fixes — adjust based on your actual columns
df["Age"] = pd.to_numeric(df["Age"], errors="coerce")
df["Date"] = pd.to_datetime(df["Date"], errors="coerce")

KeyError: 'Date'

In [ ]:
# Drop rows that are completely empty
df.dropna(how="all", inplace=True)

# Fill numeric columns
df.fillna({
    "Age": df["Age"].median()
}, inplace=True)

# Fill text columns
df.fillna({
    "Name": "Unknown"
}, inplace=True)

In [ ]:
df.info()
print(df.describe(include="all"))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Name         5 non-null      object
 1   Age          5 non-null      float64
 2   Signup Date  5 non-null      datetime64[ns]
 3   Score        5 non-null      float64
dtypes: datetime64[ns](1), float64(2), object(1)
memory usage: 292.0+ bytes
         Name        Age          Signup Date     Score
count       5   5.000000                    5   5.00000
unique      5        NaN                  NaN       NaN
top     Alice        NaN                  NaN       NaN
freq        1        NaN                  NaN       NaN
mean      NaN  34.000000  2022-01-01 00:00:00  92.00000
min       NaN  25.000000  2022-01-01 00:00:00  88.00000
25%       NaN  35.000000  2022-01-01 00:00:00  92.00000
50%       NaN  35.000000  2022-01-01 00:00:00  92.00000
75%       NaN  35.000000  2022-01-01 00:00:00  92.50000
max       NaN  40.000000  2022-01-01 00:00:00  95.50000
std       NaN   5.477226                  NaN   2.66927

### 📝 Summary

| Concept        | Tool/Function                      |
|----------------|------------------------------------|
| Detect nulls   | `df.isnull()`, `df.isnull().sum()` |
| Drop rows      | `df.dropna()`                      |
| Fill values    | `df.fillna()`                      |
| Convert types  | `pd.to_numeric()`, `pd.to_datetime()` |
| Replace values | `df.replace()`                     |