# 🧱 Column Operations: Creating, Renaming, and Dropping Columns

## 🔹 LEARNING GOALS:
- Create new columns using calculations or functions
- Rename one or multiple columns
- Drop unwanted columns safely
- Apply functions across columns using `.apply()` and lambdas

### 🏗️ 1. Setup and Sample Data

In [ ]:
import pandas as pd

data = {
    "first_name": ["Alice", "Bob", "Charlie", "David"],
    "last_name": ["Smith", "Jones", "Brown", "Wilson"],
    "math_score": [85, 90, 78, 92],
    "science_score": [88, 85, 82, 95]
}

df = pd.DataFrame(data)
df

  first_name last_name  math_score  science_score
0      Alice     Smith          85             88
1        Bob     Jones          90             85
2    Charlie     Brown          78             82
3      David    Wilson          92             95

### ➕ 2. Creating New Columns

In [ ]:
# Simple column arithmetic
df["average_score"] = (df["math_score"] + df["science_score"]) / 2
df

  first_name last_name  math_score  science_score  average_score
0      Alice     Smith          85             88           86.5
1        Bob     Jones          90             85           87.5
2    Charlie     Brown          78             82           80.0
3      David    Wilson          92             95           93.5

In [ ]:
# Create full name column
df["full_name"] = df["first_name"] + " " + df["last_name"]
df

,first_name,last_name,math_score,science_score,average_score,full_name
0,Alice,Smith,85,88,86.5,Alice Smith
1,Bob,Jones,90,85,87.5,Bob Jones
2,Charlie,Brown,78,82,80.0,Charlie Brown
3,David,Wilson,92,95,93.5,David Wilson

### ✍️ 3. Renaming Columns

In [ ]:
# Rename a single column
df.rename(columns={"math_score": "Math", "science_score": "Science"}, inplace=True)
df

  first_name last_name  Math  Science  average_score      full_name
0      Alice     Smith    85       88           86.5    Alice Smith
1        Bob     Jones    90       85           87.5      Bob Jones
2    Charlie     Brown    78       82           80.0  Charlie Brown
3      David    Wilson    92       95           93.5   David Wilson

In [ ]:
# Rename all columns to uppercase
df.columns = [col.upper() for col in df.columns]
df

  FIRST_NAME LAST_NAME  MATH  SCIENCE  AVERAGE_SCORE      FULL_NAME
0      Alice     Smith    85       88           86.5    Alice Smith
1        Bob     Jones    90       85           87.5      Bob Jones
2    Charlie     Brown    78       82           80.0  Charlie Brown
3      David    Wilson    92       95           93.5   David Wilson

### ❌ 4. Dropping Columns

In [ ]:
# Drop by name
df.drop(columns=["FULL_NAME"], inplace=True)
df

  FIRST_NAME LAST_NAME  MATH  SCIENCE  AVERAGE_SCORE
0      Alice     Smith    85       88           86.5
1        Bob     Jones    90       85           87.5
2    Charlie     Brown    78       82           80.0
3      David    Wilson    92       95           93.5

### 🔁 5. Applying Functions Across Columns

In [ ]:
# Categorize based on average score
def grade(score):
    if score >= 90:
        return "A"
    elif score >= 80:
        return "B"
    else:
        return "C"

df["GRADE"] = df["AVERAGE_SCORE"].apply(grade)
df

  FIRST_NAME LAST_NAME  MATH  SCIENCE  AVERAGE_SCORE GRADE
0      Alice     Smith    85       88           86.5     B
1        Bob     Jones    90       85           87.5     B
2    Charlie     Brown    78       82           80.0     B
3      David    Wilson    92       95           93.5     A

### 🧪 Try It Yourself

- Add a new column called `"NAME_LENGTH"` that contains the length of each `FIRST_NAME`
- Create a column `"MATH_PLUS_5"` which is the math score + 5 points bonus

In [ ]:
#1
import pandas as pd

data = {
    "FIRST_NAME": ["Alice", "Bob", "Charlie", "David"],
    "LAST_NAME": ["Smith", "Jones", "Brown", "Wilson"],
    "MATH": [85, 90, 78, 92],
    "SCIENCE": [88, 85, 82, 95]
}
=

df = pd.DataFrame(data)
df

  FIRST_NAME LAST_NAME  MATH  SCIENCE
0      Alice     Smith    85       88
1        Bob     Jones    90       85
2    Charlie     Brown    78       82
3      David    Wilson    92       95

In [ ]:
#2
df["NAME_LENGTH"] = df["FIRST_NAME"].apply(len)
df

  FIRST_NAME LAST_NAME  MATH  SCIENCE  NAME_LENGTH
0      Alice     Smith    85       88            5
1        Bob     Jones    90       85            3
2    Charlie     Brown    78       82            7
3      David    Wilson    92       95            5

In [ ]:
df["MATH_PLUS_5"] = df["MATH"] + 5
df

  FIRST_NAME LAST_NAME  MATH  SCIENCE  NAME_LENGTH  MATH_PLUS_5
0      Alice     Smith    85       88            5           90
1        Bob     Jones    90       85            3           95
2    Charlie     Brown    78       82            7           83
3      David    Wilson    92       95            5           97

### 🧠 Mini-Challenge

> Load `"data/students.csv"` and:
- Create a `"total_score"` column by summing up all numeric test columns
- Rename any columns that contain spaces (e.g., `"Test 1"`) to use underscores
- Drop any column that contains only `NaN` values

In [ ]:
import pandas as pd

data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Emma"],
    "Test 1": [85, 90, 78, 92, 88],
    "Test 2": [80, 95, 82, 89, 91],
    "Test 3": [87, 88, 79, 94, 90],
    "Extra Column": [None, None, None, None, None]  # to test NaN drop
}

df = pd.DataFrame(data)
df

      Name  Test 1  Test 2  Test 3 Extra Column
0    Alice      85      80      87         None
1      Bob      90      95      88         None
2  Charlie      78      82      79         None
3    David      92      89      94         None
4     Emma      88      91      90         None

In [ ]:
df["total_score"] = df[["Test 1", "Test 2", "Test 3"]].sum(axis=1)
df

      Name  Test 1  Test 2  Test 3 Extra Column  total_score
0    Alice      85      80      87         None          252
1      Bob      90      95      88         None          273
2  Charlie      78      82      79         None          239
3    David      92      89      94         None          275
4     Emma      88      91      90         None          269

In [ ]:
df.columns = [col.replace(" ", "_") for col in df.columns]
df

      Name  Test_1  Test_2  Test_3 Extra_Column  total_score
0    Alice      85      80      87         None          252
1      Bob      90      95      88         None          273
2  Charlie      78      82      79         None          239
3    David      92      89      94         None          275
4     Emma      88      91      90         None          269

In [ ]:
df.dropna(axis=1, how="all", inplace=True)
df

      Name  Test_1  Test_2  Test_3  total_score
0    Alice      85      80      87          252
1      Bob      90      95      88          273
2  Charlie      78      82      79          239
3    David      92      89      94          275
4     Emma      88      91      90          269

### 📝 Summary

| Action             | Method                                |
|--------------------|----------------------------------------|
| Create column       | `df["new"] = ...`                     |
| Rename column(s)    | `df.rename(columns={...})`            |
| Rename all columns  | `df.columns = [...]`                 |
| Drop column(s)      | `df.drop(columns=[...])`              |
| Apply function      | `df["col"].apply(func)`               |