# 📊 04 - Data Input and Output

Most of data science is about **loading data, exploring it, and saving results**.  
In this notebook you will learn:
- Reading CSV files with Pandas
- Inspecting DataFrames (`head`, `info`, `describe`)
- Writing data back to CSV
- Reading Excel files (if available)

## 1. Reading CSV Files

In [ ]:
import pandas as pd

# Create a small CSV for demo
data = """Name,Age,Score
Alice,23,90
Bob,25,85
Charlie,22,95
"""
with open("students.csv", "w") as f:
    f.write(data)

# Read CSV into DataFrame
df = pd.read_csv("students.csv")
df

✅ **Your Turn**: Create your own small CSV (3–5 rows) and read it into Pandas.

In [ ]:
import pandas as pd

# Create your own CSV data
data = """Name,Age,Score
Kevin,21,88
Jordan,22,92
Taylor,20,85
Chris,23,90
"""

# Write to file
with open("my_students.csv", "w") as f:
    f.write(data)

# Read into DataFrame
df = pd.read_csv("my_students.csv")
df

     Name  Age  Score
0   Kevin   21     88
1  Jordan   22     92
2  Taylor   20     85
3   Chris   23     90

## 2. Exploring DataFrames

In [ ]:
# Look at the first rows
df.head()

     Name  Age  Score
0   Kevin   21     88
1  Jordan   22     92
2  Taylor   20     85
3   Chris   23     90

In [ ]:
# Info about columns and data types
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      object
 1   Age     4 non-null      int64
 2   Score   4 non-null      int64
dtypes: int64(2), object(1)
memory usage: 228.0+ bytes

In [ ]:
# Summary statistics
df.describe()

             Age      Score
count   4.000000   4.000000
mean   21.500000  88.750000
std     1.290994   2.986079
min    20.000000  85.000000
25%    20.750000  87.250000
50%    21.500000  89.000000
75%    22.250000  90.500000
max    23.000000  92.000000

✅ **Your Turn**: Use `.head()` to preview your dataset and `.describe()` to see basic statistics.

In [ ]:
# Preview first rows
df.head()

     Name  Age  Score
0   Kevin   21     88
1  Jordan   22     92
2  Taylor   20     85
3   Chris   23     90

In [ ]:
# Summary statistics
df.describe()

             Age      Score
count   4.000000   4.000000
mean   21.500000  88.750000
std     1.290994   2.986079
min    20.000000  85.000000
25%    20.750000  87.250000
50%    21.500000  89.000000
75%    22.250000  90.500000
max    23.000000  92.000000

## 3. Writing CSV Files

In [ ]:
# Save the DataFrame to a new CSV
df.to_csv("students_copy.csv", index=False)
%ls *.csv

✅ **Your Turn**: Save your DataFrame to a CSV file called `my_data.csv`.

In [ ]:
# Save to new CSV
df.to_csv("my_data.csv", index=False)

# Confirm file exists
%ls *.csv

my_data.csv  my_students.csv

## 4. Reading Excel Files

In [ ]:
# Optional: Requires 'openpyxl' installed
# Save to Excel
df.to_excel("students.xlsx", index=False)

# Read Excel file
pd.read_excel("students.xlsx")

✅ **Your Turn**: Try saving your dataset to Excel and reading it back (if supported in your environment).

In [ ]:
# Save to Excel
df.to_excel("my_data.xlsx", index=False)

# Read Excel file
df_excel = pd.read_excel("my_data.xlsx")
df_excel

     Name  Age  Score
0   Kevin   21     88
1  Jordan   22     92
2  Taylor   20     85
3   Chris   23     90

---
### Summary
- `pd.read_csv` loads data into a DataFrame.
- Use `.head()`, `.info()`, `.describe()` to explore quickly.
- `df.to_csv` and `df.to_excel` save results.
- Pandas makes file I/O simple and reliable.